### ISSUE TITLE
Problems to install

### ISSUE THREAD

**Issue by Leomhl** [Willyham/botsapp#4]
Hello dear @Willyham, I'm with this problem. Could you help-me, please?

Print:
https://ibb.co/iNqjza

 Thank you! Have a nice day.

**Comment by marcianosr** [comment]
@Willyham Is this still working?

**Comment by Willyham** [comment]
Unfortunately the `whatsapi` package that this depends on is no longer available due to legal action taken by WhatsApp. 

I believe that somebody may have republished that package to npm under another name, but as it currently stands, no, you won't be able to run this.

**Comment by parsibox** [comment]
npm i whatsapi-republished
